version: "3.8" # optional since v1.27.0
services:
  goloop:
    container_name: goloop
    build:
      context: ../goloop
      args:
        ICONBRIDGE_VERSION: latest
        GOLOOP_IMAGE: iconloop/goloop-icon:latest
    ports:
      - "9080:9080"
    environment:
      - GOLOOP_NODE_DIR=/goloop/data/goloop
      - GOLOOP_LOG_WRITER_FILENAME=/goloop/data/log/goloop.log

  algod:
    container_name: algorand
    build:
      context: ../algod
    ports:
      - 4001:4001
